#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/camunda?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: root

#camunda 配置
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: admin
    filter:
      create: All tasks
    job-execution:
      enabled: true
    metrics:
      enabled: false
      db-reporter-activate: false